version: 2

models:

  - name: mart_general
    description: Main dataset for Power BI analyses

    columns:

      - name: order_id
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: ordered_at
        tests:
          - not_null

      - name: payment
        tests:
          - not_null

      - name: category
        tests:
          - not_null

  - name: mart_ca
    description: Analysis of revenue over time

    columns:

      - name: order_id
        tests:
          - not_null

      - name: ordered_at
        tests:
          - not_null

      - name: total_item_amount
        tests:
          - not_null

      - name: payment
        tests:
          - not_null

  - name: mart_topcity
    description: Geographic analysis of orders

    columns:

      - name: city
        tests:
          - not_null

      - name: etat
        tests:
          - not_null

      - name: payment
        tests:
          - not_null

  - name: mart_10_category_winners
    description: Analysis of product categories

    columns:

      - name: category
        tests:
          - not_null

      - name: total_item_amount
        tests:
          - not_null

  - name: mart_delivery_delay
    description: delivery delay of the orders

    columns:

      - name: order_id
        tests:
          - not_null

      - name: delai_livraison
        tests:
          - not_null

  - name: mart_customer_metrics
    description: Dataset CRM clients

    columns:

      - name: customer_id
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null

      - name: payment
        tests:
          - not_null

  - name: mart_customer_rfm
    description: Base of calcul RFM (1 to 5 )

    columns:

      - name: customer_id
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null

      - name: payment
        tests:
          - not_null

  - name: mart_avgbasket
    description: Analyst of average basket per state,city

    columns:

      - name: customer_id
        tests:
          - not_null

      - name: order_id
        tests:
          - not_null

      - name: payment
        tests:
          - not_null