version: 2

sources:
  - name: stagging # Source system name
    schema: main # Schema containing the source tables
    tables:
      - name: stg_customers # Table name as it exists in the database
      - name: stg_order_items
      - name: stg_orders
      - name: stg_payments
      - name: stg_products
