version: 2

sources:
  - name: intermediate # Source system name
    schema: main # Schema containing the source tables
    tables:
      - name: int_delivery # Table name as it exists in the database
      - name: int_sales
      - name: int_customers_orders
